export default {
  interests: [
    'developer',
    'soccer',
    'fitness',
    'good vibes',
    'immigrant',
    'first-generation',
    'social',
    'resilient',
    'driven',
    'philosophy',
    'food junkie',
    'one on one\'s',
    'ecuadorean',
    'animal lover',
    'basketball',
    'millenial',
    'open-minded',
    'engineer',
    'technologist',
    'mellow',
    'pisces',
    'motivator',
    'law of attraction',
    'self-taught',
  ],
  fonts: [
    "'Gamja Flower', cursive",
    "'Russian Display', cursive",
    'Shadows Into Light', 'Lobster',
    "'Cinzel', serif",
    "'Orbitron', sans-serif",
    "'Permanent Marker', cursive",
    "Lobster', cursive",
    "Satisfy', cursive",
  ],
  fontWeights: [
    'lighter',
    'normal',
    'bold',
  ],
}
